import type { AppProps } from 'next/app'
import { NextPageWithLayout } from '@/types'
import Head from 'next/head'
 
type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout
}
 
export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page) => page)

  return (
    <div>
      <Head>
        <title>Marcello Luatti | Frontend Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="react, next, typescript, ux" />
      </Head>
      {getLayout(<Component {...pageProps} />)}
    </div>
  );
}