import type { AppProps } from 'next/app'
import { NextPageWithLayout } from '@/types'
import Head from 'next/head'
import GlobalStyles from '@/styles/global'
import Layout from '@/components/Layout/Root'

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout,
  metaTitle: string
}
 
export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page) => page)

  return (
    <div>
      <Head>
        <title>Marcello Luatti | Frontend Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="react, next, typescript, ux" />
        <meta property="viewport" content="width=device-width,minimum-scale=1,initial-scale=1" />
        <meta property="og:type" content="website" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <GlobalStyles />
      <Layout>
        {getLayout(<Component {...pageProps} />)}
      </Layout>
    </div>
  );
}