name: Build once a pr is opened vs main

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Build Next.js
        run: npm run build

      - name: Checking that index.html exists in the out folder
        run: |
          if [ ! -f ./out/index.html ]; then
            echo "next export phase failed"
            exit 1
          fi
